const helpCenterLinks = [
    { label: 'Cách tạo tài khoản', href: 'https://www.facebook.com/help/570785306433644/?helpref=hc_fnav' },
    { label: 'Trang cá nhân của bạn', href: 'https://www.facebook.com/help/396528481579093/?helpref=hc_fnav' },
    { label: 'Kết bạn', href: 'https://www.facebook.com/help/1540345696275090/?helpref=hc_fnav' },
    { label: 'Hẹn hò trên Facebook', href: 'https://www.facebook.com/help/312959615934334/?helpref=hc_fnav' },
    { label: 'Trang chủ của bạn', href: 'https://www.facebook.com/help/753701661398957/?helpref=hc_fnav' },
    { label: 'Nhắn tin', href: 'https://www.facebook.com/help/1071984682876123/?helpref=hc_fnav' },
    { label: 'Reels', href: 'https://www.facebook.com/help/753046815962474/?helpref=hc_fnav' },
    { label: 'Tin', href: 'https://www.facebook.com/help/862926927385914/?helpref=hc_fnav' },
    { label: 'Ảnh', href: 'https://www.facebook.com/help/1069521513115444/?helpref=hc_fnav' },
    { label: 'Video', href: 'https://www.facebook.com/help/1041553655923544/?helpref=hc_fnav' },
    { label: 'Game', href: 'https://www.facebook.com/help/2402655169966967/?helpref=hc_fnav' },
    { label: 'Trang', href: 'https://www.facebook.com/help/282489752085908/?helpref=hc_fnav' },
    { label: 'Nhóm', href: 'https://www.facebook.com/help/1629740080681586/?helpref=hc_fnav' },
    { label: 'Sự kiện', href: 'https://www.facebook.com/help/1076296042409786/?helpref=hc_fnav' },
    { label: 'Meta Pay', href: 'https://www.facebook.com/help/1434403039959381/?helpref=hc_fnav' },
    { label: 'Marketplace', href: 'https://www.facebook.com/help/1713241952104830/?helpref=hc_fnav' },
    { label: 'Ứng dụng', href: 'https://www.facebook.com/help/1642635852727373/?helpref=hc_fnav' },
    { label: 'Ứng dụng di động Facebook', href: 'https://www.facebook.com/help/866249956813928/?helpref=hc_fnav' },
    { label: 'Trợ năng', href: 'https://www.facebook.com/help/273947702950567/?helpref=hc_fnav' },
];

const countryOptions = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    "Cote d'Ivoire",
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];

export { helpCenterLinks, countryOptions };
